language: node_js
node_js:
  - "lts/*"
install:
  - yarn install
script:
  - yarn test
  - yarn build
cache:
  yarn: true
  directories:
    - "node_modules"
notifications:
  email:
    on_success: never
    on_failure: always

